apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: college-system
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "college-backend"
        metrics_path: /metrics
        static_configs:
          - targets:
              - backend.college-system.svc.cluster.local:5000

      - job_name: "prometheus"
        static_configs:
          - targets:
              - prometheus:9090
