apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: college-system
type: Opaque
stringData:
  DB_USER: college_admin
  DB_PASSWORD: college_password
  JWT_SECRET: change_me_before_demo
